-- Smart Classroom System Database Script (18-Track Update)
-- Generated by Antigravity
-- Works with any database (local: smart_classroom, Railway: railway)

-- Table: classrooms
CREATE TABLE IF NOT EXISTS classrooms (
    id INT AUTO_INCREMENT PRIMARY KEY,
    room_name VARCHAR(50) NOT NULL UNIQUE,
    floor VARCHAR(20),
    capacity INT,
    status ENUM('available', 'occupied') DEFAULT 'available',
    occupied_by VARCHAR(100),
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Table: users
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100),
    role ENUM('admin', 'cr', 'faculty', 'student'),
    username VARCHAR(50) UNIQUE,
    password VARCHAR(255)
);

-- Table: subjects
CREATE TABLE IF NOT EXISTS subjects (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT,
    code VARCHAR(20),
    name VARCHAR(100),
    faculty VARCHAR(100),
    total_required_classes INT DEFAULT 40,
    completed_classes INT DEFAULT 0,
    color_code VARCHAR(10),
    FOREIGN KEY (user_id) REFERENCES users(id),
    UNIQUE(user_id, code)
);

-- Table: timetable
CREATE TABLE IF NOT EXISTS timetable (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT,
    day ENUM('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday') NOT NULL,
    period_no INT NOT NULL,
    time_from TIME,
    time_to TIME,
    subject_code VARCHAR(20),
    room_id INT,
    batch VARCHAR(10) DEFAULT 'ALL',
    is_lab TINYINT(1) DEFAULT 0,
    notes VARCHAR(200),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (room_id) REFERENCES classrooms(id)
);

-- Table: attendance_log
CREATE TABLE IF NOT EXISTS attendance_log (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT,
    subject_code VARCHAR(20),
    timetable_id INT,
    date DATE,
    period_no INT,
    status ENUM('conducted', 'cancelled', 'extra') DEFAULT 'conducted',
    notes VARCHAR(200),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (timetable_id) REFERENCES timetable(id)
);



-- Truncate tables for a clean seed
    SET FOREIGN_KEY_CHECKS = 0;
    TRUNCATE TABLE attendance_log;
    TRUNCATE TABLE timetable;
    TRUNCATE TABLE subjects;
    TRUNCATE TABLE classrooms;
    TRUNCATE TABLE users;
    SET FOREIGN_KEY_CHECKS = 1;

-- Seed Classrooms
-- L-01 to L-20 (3rd floor, cap 60)
INSERT INTO classrooms (room_name, floor, capacity) VALUES 
('L-01', '3rd', 60), ('L-02', '3rd', 60), ('L-03', '3rd', 60), ('L-04', '3rd', 60), ('L-05', '3rd', 60),
('L-06', '3rd', 60), ('L-07', '3rd', 60), ('L-08', '3rd', 60), ('L-09', '3rd', 60), ('L-10', '3rd', 60),
('L-11', '3rd', 60), ('L-12', '3rd', 60), ('L-13', '3rd', 60), ('L-14', '3rd', 60), ('L-15', '3rd', 60),
('L-16', '3rd', 60), ('L-17', '3rd', 60), ('L-18', '3rd', 60), ('L-19', '3rd', 60), ('L-20', '3rd', 60);

-- Labs: LAB-1 to LAB-5 + HPC LAB (2nd floor, cap 30)
INSERT INTO classrooms (room_name, floor, capacity) VALUES 
('LAB-1', '2nd', 30), ('LAB-2', '2nd', 30), ('LAB-3', '2nd', 30), ('LAB-4', '2nd', 30), ('LAB-5', '2nd', 30), ('HPC LAB', '2nd', 30);

-- L-21 to L-38 + Seminar S-01 to S-05
INSERT INTO classrooms (room_name, floor, capacity) VALUES 
('L-21', '2nd', 60), ('L-22', '2nd', 60), ('L-23', '2nd', 60), ('L-24', '2nd', 60), ('L-25', '2nd', 60),
('L-26', '2nd', 60), ('L-27', '2nd', 60), ('L-28', '2nd', 60), ('L-29', '1st', 60), ('L-30', '1st', 60),
('L-31', '1st', 60), ('L-32', '1st', 60), ('L-33', '1st', 60), ('L-34', '1st', 60), ('L-35', '1st', 60),
('L-36', '1st', 60), ('L-37', '1st', 60), ('L-38', '1st', 60);

INSERT INTO classrooms (room_name, floor, capacity) VALUES 
('S-01', 'Ground', 150), ('S-02', 'Ground', 150), ('S-03', 'Ground', 150), ('S-04', 'Ground', 150), ('S-05', 'Ground', 150);

-- Seed Users
INSERT INTO users (id, name, role, username, password) VALUES 
(1, 'Admin User', 'admin', 'admin', MD5('admin123')),
(2, 'CR 1', 'cr', 'cr1', MD5('cr123')),
(3, 'CR 2', 'cr', 'cr2', MD5('cr123')),
(4, 'CR 3', 'cr', 'cr3', MD5('cr123')),
(5, 'CR 4', 'cr', 'cr4', MD5('cr123')),
(6, 'CR 5', 'cr', 'cr5', MD5('cr123')),
(7, 'CR 6', 'cr', 'cr6', MD5('cr123')),
(8, 'Student', 'student', 'student', MD5('student123'));

-- Seed Subjects (18 Variations: Theory, Batch A1, Batch A2)
-- Using counts provided by user
INSERT INTO subjects (user_id, code, name, faculty, total_required_classes, completed_classes, color_code) VALUES 
(6, 'DBMS_T', 'Database Management System (T)', 'Prof. Tasneem Wasiha', 30, 24, '#9b59b6'),
(6, 'DBMS_P1', 'Database Management System (A1)', 'Prof. Tasneem Wasiha', 30, 28, '#9b59b6'),
(6, 'DBMS_P2', 'Database Management System (A2)', 'Prof. Tasneem Wasiha', 30, 26, '#9b59b6'),
(6, 'WP_T', 'Web Programming (T)', 'Prof. Vinayak Mukkawar', 30, 25, '#2ecc71'),
(6, 'WP_P1', 'Web Programming (A1)', 'Prof. Vinayak Mukkawar', 30, 26, '#2ecc71'),
(6, 'WP_P2', 'Web Programming (A2)', 'Prof. Vinayak Mukkawar', 30, 28, '#2ecc71'),
(6, 'SM_T', 'Statistical Mathematics (T)', 'Dr. Vidyasagar Voorugonda', 30, 26, '#e74c3c'),
(6, 'SM_P1', 'Statistical Mathematics (A1)', 'Dr. Vidyasagar Voorugonda', 30, 28, '#e74c3c'),
(6, 'SM_P2', 'Statistical Mathematics (A2)', 'Dr. Vidyasagar Voorugonda', 30, 28, '#e74c3c'),
(6, 'IDSIA_T', 'Intro to Signal, Data & Image Analysis (T)', 'Prof. B P Sharma', 45, 39, '#f39c12'),
(6, 'IDSIA_P1', 'Intro to Signal, Data & Image Analysis (A1)', 'Prof. B P Sharma', 30, 30, '#f39c12'),
(6, 'IDSIA_P2', 'Intro to Signal, Data & Image Analysis (A2)', 'Prof. B P Sharma', 30, 28, '#f39c12'),
(6, 'ML_T', 'Machine Learning (T)', 'Dr. Naresh Vurukonda', 45, 37, '#3498db'),
(6, 'ML_P1', 'Machine Learning (A1)', 'Dr. Naresh Vurukonda', 30, 30, '#3498db'),
(6, 'ML_P2', 'Machine Learning (A2)', 'Dr. Naresh Vurukonda', 30, 26, '#3498db'),
(6, 'DHV_T', 'Data Handling & Visualisation (T)', 'Prof. Anshi Bajaj', 15, 11, '#1abc9c'),
(6, 'DHV_P1', 'Data Handling & Visualisation (A1)', 'Prof. Anshi Bajaj', 30, 22, '#1abc9c'),
(6, 'DHV_P2', 'Data Handling & Visualisation (A2)', 'Prof. Anshi Bajaj', 30, 26, '#1abc9c');



-- Seed Timetable Slots (Updated to match image grid)
INSERT INTO timetable (user_id, day, period_no, time_from, time_to, subject_code, room_id, batch, is_lab) VALUES 
-- Monday
(6, 'Monday', 1, '09:15:00', '10:15:00', NULL, NULL, 'ALL', 0), 
(6, 'Monday', 2, '10:15:00', '11:15:00', 'DBMS_P1', (SELECT id FROM classrooms WHERE room_name='LAB-1'), 'A1', 1),
(6, 'Monday', 2, '10:15:00', '11:15:00', 'IDSIA_P2', (SELECT id FROM classrooms WHERE room_name='LAB-3'), 'A2', 1),
(6, 'Monday', 3, '11:15:00', '12:15:00', 'DBMS_P1', (SELECT id FROM classrooms WHERE room_name='LAB-1'), 'A1', 1),
(6, 'Monday', 3, '11:15:00', '12:15:00', 'IDSIA_P2', (SELECT id FROM classrooms WHERE room_name='LAB-3'), 'A2', 1),
(6, 'Monday', 5, '13:00:00', '14:00:00', 'SM_P2', (SELECT id FROM classrooms WHERE room_name='LAB-2'), 'A2', 1),
(6, 'Monday', 5, '13:00:00', '14:00:00', 'ML_P1', (SELECT id FROM classrooms WHERE room_name='LAB-5'), 'A1', 1),
(6, 'Monday', 6, '14:00:00', '15:00:00', 'SM_P2', (SELECT id FROM classrooms WHERE room_name='LAB-2'), 'A2', 1),
(6, 'Monday', 6, '14:00:00', '15:00:00', 'ML_P1', (SELECT id FROM classrooms WHERE room_name='LAB-5'), 'A1', 1),
(6, 'Monday', 7, '15:00:00', '16:00:00', 'SM_T', (SELECT id FROM classrooms WHERE room_name='L-15'), 'ALL', 0),
(6, 'Monday', 8, '16:00:00', '17:00:00', 'ML_T', (SELECT id FROM classrooms WHERE room_name='L-15'), 'ALL', 0),

-- Tuesday
(6, 'Tuesday', 1, '09:15:00', '10:15:00', 'IDSIA_P1', (SELECT id FROM classrooms WHERE room_name='LAB-3'), 'A1', 1),
(6, 'Tuesday', 1, '09:15:00', '10:15:00', 'DBMS_P2', (SELECT id FROM classrooms WHERE room_name='LAB-1'), 'A2', 1),
(6, 'Tuesday', 2, '10:15:00', '11:15:00', 'IDSIA_P1', (SELECT id FROM classrooms WHERE room_name='LAB-3'), 'A1', 1),
(6, 'Tuesday', 2, '10:15:00', '11:15:00', 'DBMS_P2', (SELECT id FROM classrooms WHERE room_name='LAB-1'), 'A2', 1),
(6, 'Tuesday', 3, '11:15:00', '12:15:00', 'IDSIA_T', (SELECT id FROM classrooms WHERE room_name='L-15'), 'ALL', 0),
(6, 'Tuesday', 5, '13:00:00', '14:00:00', 'DHV_P2', (SELECT id FROM classrooms WHERE room_name='LAB-4'), 'A2', 1),
(6, 'Tuesday', 5, '13:00:00', '14:00:00', 'WP_P1', (SELECT id FROM classrooms WHERE room_name='LAB-2'), 'A1', 1),
(6, 'Tuesday', 6, '14:00:00', '15:00:00', 'DHV_P2', (SELECT id FROM classrooms WHERE room_name='LAB-4'), 'A2', 1),
(6, 'Tuesday', 6, '14:00:00', '15:00:00', 'WP_P1', (SELECT id FROM classrooms WHERE room_name='LAB-2'), 'A1', 1),
(6, 'Tuesday', 7, '15:00:00', '16:00:00', 'ML_T', (SELECT id FROM classrooms WHERE room_name='L-15'), 'ALL', 0),
(6, 'Tuesday', 8, '16:00:00', '17:00:00', NULL, NULL, 'ALL', 0),

-- Wednesday
(6, 'Wednesday', 1, '09:15:00', '10:15:00', 'DHV_T', (SELECT id FROM classrooms WHERE room_name='L-15'), 'ALL', 0),
(6, 'Wednesday', 2, '10:15:00', '11:15:00', 'DBMS_T', (SELECT id FROM classrooms WHERE room_name='L-15'), 'ALL', 0),
(6, 'Wednesday', 3, '11:15:00', '12:15:00', 'SM_T', (SELECT id FROM classrooms WHERE room_name='L-15'), 'ALL', 0),
(6, 'Wednesday', 5, '13:00:00', '14:00:00', 'ML_T', (SELECT id FROM classrooms WHERE room_name='L-15'), 'ALL', 0),
(6, 'Wednesday', 6, '14:00:00', '15:00:00', 'IDSIA_T', (SELECT id FROM classrooms WHERE room_name='L-15'), 'ALL', 0),
(6, 'Wednesday', 7, '15:00:00', '16:00:00', 'SM_P1', (SELECT id FROM classrooms WHERE room_name='LAB-1'), 'A1', 1),
(6, 'Wednesday', 7, '15:00:00', '16:00:00', 'ML_P2', (SELECT id FROM classrooms WHERE room_name='LAB-3'), 'A2', 1),
(6, 'Wednesday', 8, '16:00:00', '17:00:00', 'SM_P1', (SELECT id FROM classrooms WHERE room_name='LAB-1'), 'A1', 1),
(6, 'Wednesday', 8, '16:00:00', '17:00:00', 'ML_P2', (SELECT id FROM classrooms WHERE room_name='LAB-3'), 'A2', 1),

-- Thursday
(6, 'Thursday', 1, '09:15:00', '10:15:00', NULL, NULL, 'ALL', 0),
(6, 'Thursday', 2, '10:15:00', '11:15:00', 'DHV_T', (SELECT id FROM classrooms WHERE room_name='L-15'), 'ALL', 0),
(6, 'Thursday', 3, '11:15:00', '12:15:00', NULL, NULL, 'ALL', 0),
(6, 'Thursday', 5, '13:00:00', '14:00:00', 'DBMS_T', (SELECT id FROM classrooms WHERE room_name='L-15'), 'ALL', 0),
(6, 'Thursday', 6, '14:00:00', '15:00:00', NULL, NULL, 'ALL', 0),
(6, 'Thursday', 7, '15:00:00', '16:00:00', 'DHV_P1', (SELECT id FROM classrooms WHERE room_name='LAB-1'), 'A1', 1),
(6, 'Thursday', 7, '15:00:00', '16:00:00', 'WP_P2', (SELECT id FROM classrooms WHERE room_name='LAB-3'), 'A2', 1),
(6, 'Thursday', 8, '16:00:00', '17:00:00', 'DHV_P1', (SELECT id FROM classrooms WHERE room_name='LAB-1'), 'A1', 1),
(6, 'Thursday', 8, '16:00:00', '17:00:00', 'WP_P2', (SELECT id FROM classrooms WHERE room_name='LAB-3'), 'A2', 1),

-- Friday
(6, 'Friday', 1, '09:15:00', '10:15:00', 'WP_T', (SELECT id FROM classrooms WHERE room_name='L-15'), 'ALL', 0),
(6, 'Friday', 2, '10:15:00', '11:15:00', 'WP_T', (SELECT id FROM classrooms WHERE room_name='L-15'), 'ALL', 0),
(6, 'Friday', 3, '11:15:00', '12:15:00', 'IDSIA_T', (SELECT id FROM classrooms WHERE room_name='L-15'), 'ALL', 0),
(6, 'Friday', 5, '13:00:00', '14:00:00', NULL, NULL, 'ALL', 0),
(6, 'Friday', 6, '14:00:00', '15:00:00', NULL, NULL, 'ALL', 0),
(6, 'Friday', 7, '15:00:00', '16:00:00', NULL, NULL, 'ALL', 0),
(6, 'Friday', 8, '16:00:00', '17:00:00', NULL, NULL, 'ALL', 0);
